name: C++ Library Template CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Trigger the worflow on push or pull request by only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Cpp Format and Lint Check
        if: matrix.os == 'ubuntu-20.04'
        run: |
          # install clang-format
          sudo curl -L https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-22538c65/clang-format-8_linux-amd64 --output /usr/bin/clang-format
          sudo chmod +x /usr/bin/clang-format

          # run format
          cd ${GITHUB_WORKSPACE}
          find ./src  -name "*.h" | xargs clang-format -i --style=file
          # find ./src -name "*.cc" | xargs clang-format -i --style=file

          # validate format
          function prepend() { while read line; do echo "${1}${line}"; done; }

          GIT_DIFF=$(git diff --ignore-submodules)
          if [[ -n $GIT_DIFF ]]; then
            echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
            echo "| clang-format failures found!"
            echo "|"
            echo "$GIT_DIFF" | prepend "| "
            echo "|"
            echo "| Run: "
            echo "|"
            echo "|    make clformat"
            echo "|"
            echo "| to fix this error."
            echo "|"
            echo "| Ensure you are working with clang-format-8, which can be obtained from"
            echo "|"
            echo "|    https://github.com/muttleyxd/clang-tools-static-binaries/releases"
            echo "|"
            echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
            exit -1
          fi

      - name: Install GraphScope
        run: |
          pip3 install graphscope pytest --user

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: true

      - name: Build Libraries
        run: |
          cd ${GITHUB_WORKSPACE}
          mkdir build && cd build && cmake .. && make -j4

      - name: Test App on GraphScope
        run: |
          cd ${GITHUB_WORKSPACE}
          # package vertex_data context app
          cd build && make vertex_data
          # test
          make test
